### ISSUE TITLE
Use CocoaPods configuration APIs

### ISSUE THREAD

**Issue by OlegAnghelov** [rs/SDWebImage#1260]
Hi guys!
First of all thanks for the marvellous job of maintaining this great library!

Secondly, I want to point out that dues to some specifics of this library, there are some issues with integrating it with pods.
For example this:
https://github.com/rs/SDWebImage/issues/1122

There is no clean solution at the moment.
But the pods have now a very flexible API. One of those are the "configurations" and "subspecs".
For  example here is how calabash handles it:
`pod 'Calabash', :configurations => ['Calabash']`

Also HockeyApp did some great job:
`pod "HockeySDK", :subspecs => ['CrashOnlyLib']`

I think it would be just awesome if we could use your library in pods, without doing all those "compile, drag and drop" solutions.
This would open great opportunities with all CI integrations and project maintenance problems.

What do you think?

**Comment by bpoplauschi** [comment]
We do have subspecs (i.e `Core` and `WebP`). Are they not sufficient? I think I'm missing the issue. WebP (from what I know) can be included via Cocoapods.

**Comment by OlegAnghelov** [comment]
Thanks a lot for the response.
Well this is what happened, we included it via Cocoapods and it was showing that SD_WEBP macros was not set, and AFAIK there is no way to setup macroses in a pod. Even if there is, it's not going to be tracked by git. 
If you do have subspecs, can you please provide some documentation for it? Or just help find it?

**Comment by bpoplauschi** [comment]
Usually, to see which subspecs are available in a pod, you can run `pod search SDWebImage` and look at the output:
```
Asynchronous image downloader with cache support with an UIImageView category.
   pod 'SDWebImage', '~> 3.7.3'
   - Homepage: https://github.com/rs/SDWebImage
   - Source:   https://github.com/rs/SDWebImage.git
   - Versions: 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6, 3.5.4, 3.5.2, 3.5.1, 3.5, 3.4, 3.3, 3.2, 3.1, 3.0, 2.7.4, 2.7, 2.6, 2.5, 2.4 [master repo]
   - Subspecs:
     - SDWebImage/Core (3.7.3)
     - SDWebImage/MapKit (3.7.3)
     - SDWebImage/WebP (3.7.3)
```

or just look directly at [the podspec file](https://github.com/rs/SDWebImage/blob/master/SDWebImage.podspec).

If you want to include WebP, you should probably add to your Podfile: `pod 'SDWebImage/WebP'`. That will include the `SD_WEBP` macro definition.
